### ISSUE TITLE
fyi: the blog post linked in repo, docs, elsewhere  is unavailable 

### ISSUE THREAD

**Issue by hanleybrand** [Microsoft/vsminecraft#6]
http://blogs.msdn.com/b/visualstudio/archive/2015/04/30/hello-minecraft-modders-visual-studio-loves-minecraft.aspx

I googled and found a mirror:  https://jameshendersoninfo.wordpress.com/2015/05/01/hello-minecraft-modders-visual-studio/

**Comment by mluparu** [comment]
It should be available now. I updated it to clarify that mods in Minecraft remain officially unsupported.
